version: '3'

services:
  express-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      - DB_HOST=192.168.31.23
      - DB_USER=speedy
      - DB_PASSWORD=password
      - DB_NAME=speedtest_tracker
    restart: always